
#ifdef HAVE_CONFIG_H
#include "../ext_config.h"
#endif

#include <php.h>
#include "../php_ext.h"
#include "../ext.h"

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"
#include "kernel/object.h"
#include "kernel/memory.h"
#include "kernel/fcall.h"
#include "kernel/operators.h"
#include "ext/spl/spl_exceptions.h"
#include "kernel/exception.h"
#include "kernel/array.h"


/**
 * This file is part of the Hal library
 *
 * (c) Ben Longden <ben@nocarrier.co.uk
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Hal
 */
/**
 * Hal\Resource
 * The Hal resource document class
 *
 * @package Hal
 * @author Ben Longden <ben@nocarrier.co.uk>
 * @author Brandon Lamb <brandon@brandonlamb.com>
 */
ZEPHIR_INIT_CLASS(Hal_Resource) {

	ZEPHIR_REGISTER_CLASS(Hal, Resource, hal, resource, hal_resource_method_entry, 0);

/**
     * The uri represented by this representation.
     *
     * @var string
     */
	zend_declare_property_null(hal_resource_ce, SL("uri"), ZEND_ACC_PROTECTED TSRMLS_CC);
/**
     * The data for this resource. An associative array of key value pairs.
     *
     * ["price" => 30.00, "colour" => "blue"]
     *
     * @var array
     */
	zend_declare_property_null(hal_resource_ce, SL("data"), ZEND_ACC_PROTECTED TSRMLS_CC);
/**
     * An array of embedded Hal objects representing embedded resources.
     *
     * @var array
     */
	zend_declare_property_null(hal_resource_ce, SL("resources"), ZEND_ACC_PROTECTED TSRMLS_CC);
/**
     * A collection of Hal\Link objects keyed by the link relation to this resource.
     *
     * ["next" => [Hal\Link]]
     *
     * @var Hal\Collection\Link
     */
	zend_declare_property_null(hal_resource_ce, SL("links"), ZEND_ACC_PROTECTED TSRMLS_CC);

	return SUCCESS;

}

/**
 * Construct a new Hal\Resource object from an array of data. You can markup the
 * data array with certain keys and values in order to affect the
 * generated JSON or XML documents if required to do so.
 *
 * "@" prefix on any array key will cause the value to be set as an
 * attribute on the XML element generated by the parent. i.e, array("x" =>
 * array("@href" => "http://url")) will yield <x href="http://url"></x> in
 * the XML representation. The @ prefix will be stripped from the JSON
 * representation.
 *
 * Specifying the key "value" will cause the value of this key to be set as
 * the value of the XML element instead of a child. i.e, array("x" =>
 * array("value" => "example")) will yield <x>example</x> in the XML
 * representation. This will not affect the JSON representation.
 *
 * @param string uri
 * @param array data
 */
PHP_METHOD(Hal_Resource, __construct) {

	zval *uri_param = NULL, *data = NULL, *_0 = NULL, *_1;
	zval *uri = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 0, 2, &uri_param, &data);

	if (!uri_param || Z_TYPE_P(uri_param) == IS_NULL) {
		ZEPHIR_INIT_VAR(uri);
		ZVAL_EMPTY_STRING(uri);
	} else {
		zephir_get_strval(uri, uri_param);
	}
	if (!data || Z_TYPE_P(data) == IS_NULL) {
		data = ZEPHIR_GLOBAL(global_null);
	}


	if ((Z_TYPE_P(data) == IS_ARRAY)) {
		zephir_update_property_this(this_ptr, SL("data"), data TSRMLS_CC);
	} else {
		ZEPHIR_INIT_VAR(_0);
		array_init(_0);
		zephir_update_property_this(this_ptr, SL("data"), _0 TSRMLS_CC);
	}
	zephir_update_property_this(this_ptr, SL("uri"), uri TSRMLS_CC);
	ZEPHIR_INIT_NVAR(_0);
	object_init_ex(_0, hal_collection_resource_ce);
	zephir_call_method_noret(_0, "__construct");
	zephir_update_property_this(this_ptr, SL("resources"), _0 TSRMLS_CC);
	ZEPHIR_INIT_VAR(_1);
	object_init_ex(_1, hal_collection_link_ce);
	zephir_call_method_noret(_1, "__construct");
	zephir_update_property_this(this_ptr, SL("links"), _1 TSRMLS_CC);
	ZEPHIR_MM_RESTORE();

}

/**
 * Get resource"s URI.
 *
 * @return string
 */
PHP_METHOD(Hal_Resource, getUri) {


	RETURN_MEMBER(this_ptr, "uri");

}

/**
 * Return an array of data (key => value pairs) representing this resource.
 *
 * @return array
 */
PHP_METHOD(Hal_Resource, getData) {


	RETURN_MEMBER(this_ptr, "data");

}

/**
 * Return an array of Hal\Resource objected embedded in this one.
 *
 * @return Hal\Collection\Resource A collection of Hal\Resource
 */
PHP_METHOD(Hal_Resource, getResources) {


	RETURN_MEMBER(this_ptr, "resources");

}

/**
 * Return an array of Hal\Link objects representing resources related to this one.
 *
 * @return Hal\Collection\Link A collection of Hal\Link
 */
PHP_METHOD(Hal_Resource, getLinks) {


	RETURN_MEMBER(this_ptr, "links");

}

/**
 * Add an embedded resource, identified by rel and represented by resource.
 *
 * @param string rel
 * @param Hal\Resource resource
 * @param bool multi
 * @return Hal\Resource
 */
PHP_METHOD(Hal_Resource, addResource) {

	zend_bool multi;
	zval *rel_param = NULL, *resource = NULL, *multi_param = NULL, *_0;
	zval *rel = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 1, 2, &rel_param, &resource, &multi_param);

		if (Z_TYPE_P(rel_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'rel' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		rel = rel_param;

	if (!resource || Z_TYPE_P(resource) == IS_NULL) {
		ZEPHIR_CPY_WRT(resource, ZEPHIR_GLOBAL(global_null));
	}
	ZEPHIR_SEPARATE_PARAM(resource);
	if (!multi_param || Z_TYPE_P(multi_param) == IS_NULL) {
		multi = 1;
	} else {
		multi = zephir_get_boolval(multi_param);
	}


	if ((Z_TYPE_P(resource) == IS_NULL)) {
		ZEPHIR_INIT_NVAR(resource);
		object_init_ex(resource, hal_resource_ce);
		zephir_call_method_noret(resource, "__construct");
	}
	_0 = zephir_fetch_nproperty_this(this_ptr, SL("resources"), PH_NOISY_CC);
	zephir_call_method_p3_noret(_0, "add", rel, resource, (multi ? ZEPHIR_GLOBAL(global_true) : ZEPHIR_GLOBAL(global_false)));
	RETURN_THIS();

}

/**
 * Lookup and return an array of Hal\Resource objects for a given relation.
 *
 * @param string rel The resource relation required
 * @return array|bool Array of Hal\Resource objects if found. Otherwise false.
 */
PHP_METHOD(Hal_Resource, getResource) {

	zval *rel_param = NULL, *_0;
	zval *rel = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 1, 0, &rel_param);

		if (Z_TYPE_P(rel_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'rel' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		rel = rel_param;



	_0 = zephir_fetch_nproperty_this(this_ptr, SL("resources"), PH_NOISY_CC);
	zephir_call_method_p1(return_value, _0, "get", rel);
	RETURN_MM();

}

/**
 * Add a link to the resource, identified by rel, located at uri.
 *
 * @param string rel
 * @param string uri
 * @param array attributes Other attributes, as defined by HAL spec and RFC 5988.
 * @return Hal\Resource
 */
PHP_METHOD(Hal_Resource, addLink) {

	zval *rel_param = NULL, *uri_param = NULL, *attributes = NULL, *link, *_0;
	zval *rel = NULL, *uri = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 2, 1, &rel_param, &uri_param, &attributes);

		if (Z_TYPE_P(rel_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'rel' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		rel = rel_param;

		if (Z_TYPE_P(uri_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'uri' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		uri = uri_param;

	if (!attributes || Z_TYPE_P(attributes) == IS_NULL) {
		attributes = ZEPHIR_GLOBAL(global_null);
	}


	ZEPHIR_INIT_VAR(link);
	object_init_ex(link, hal_link_ce);
	zephir_call_method_p2_noret(link, "__construct", uri, attributes);
	_0 = zephir_fetch_nproperty_this(this_ptr, SL("links"), PH_NOISY_CC);
	zephir_call_method_p2_noret(_0, "add", rel, link);
	RETURN_THIS();

}

/**
 * Lookup and return an array of Hal\Link objects for a given relation.  Will also resolve CURIE rels if required.
 *
 * @param string rel The link relation required
 * @return array|bool Array of Hal\Link objects if found. Otherwise false.
 */
PHP_METHOD(Hal_Resource, getLink) {

	zval *rel_param = NULL, *_0;
	zval *rel = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 1, 0, &rel_param);

		if (Z_TYPE_P(rel_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'rel' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		rel = rel_param;



	_0 = zephir_fetch_nproperty_this(this_ptr, SL("links"), PH_NOISY_CC);
	zephir_call_method_p1(return_value, _0, "get", rel);
	RETURN_MM();

}

/**
 * Create a CURIE link template, used for abbreviating custom link relations.
 *
 * $hal->addCurie("acme", "http://.../rels/{rel}");
 * $hal->addLink("acme:test", "http://.../test");
 *
 * @param string name
 * @param string uri
 * @return Hal\Resource
 */
PHP_METHOD(Hal_Resource, addCurie) {

	zval *name_param = NULL, *uri_param = NULL, *_0, *_1;
	zval *name = NULL, *uri = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 2, 0, &name_param, &uri_param);

		if (Z_TYPE_P(name_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'name' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		name = name_param;

		if (Z_TYPE_P(uri_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'uri' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		uri = uri_param;



	ZEPHIR_INIT_VAR(_0);
	array_init(_0);
	zephir_array_update_string(&_0, SL("name"), &name, PH_COPY | PH_SEPARATE);
	zephir_array_update_string(&_0, SL("templated"), &ZEPHIR_GLOBAL(global_true), PH_COPY | PH_SEPARATE);
	ZEPHIR_INIT_VAR(_1);
	ZVAL_STRING(_1, "curies", 1);
	zephir_call_method_p3_noret(this_ptr, "addlink", _1, uri, _0);
	RETURN_THIS();

}

/**
 * Fetch a curie if it exists
 *
 * @param string rel
 * @todo - implement later
 */
PHP_METHOD(Hal_Resource, getCurie) {

	zval *rel_param = NULL;
	zval *rel = NULL;

	ZEPHIR_MM_GROW();
	zephir_fetch_params(1, 1, 0, &rel_param);

		if (Z_TYPE_P(rel_param) != IS_STRING) {
				zephir_throw_exception_string(spl_ce_InvalidArgumentException, SL("Parameter 'rel' must be a string") TSRMLS_CC);
				RETURN_MM_NULL();
		}

		rel = rel_param;



	RETURN_CTOR(rel);

}

