<?php
/**
 * This file is part of the Hal library
 *
 * (c) Ben Longden <ben@nocarrier.co.uk
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Hal
 */

namespace Hal;

/**
 * Hal\Resource
 * The Hal resource document class
 *
 * @package Hal
 * @author Ben Longden <ben@nocarrier.co.uk>
 * @author Brandon Lamb <brandon@brandonlamb.com>
 */

class Resource
{
    /**
     * The uri represented by this representation.
     *
     * @var string
     */
    protected $uri;

    /**
     * The data for this resource. An associative array of key value pairs.
     *
     * ["price" => 30.00, "colour" => "blue"]
     *
     * @var array
     */
    protected $data;

    /**
     * An array of embedded Hal objects representing embedded resources.
     *
     * @var array
     */
    protected $resources;

    /**
     * A collection of Hal\Link objects keyed by the link relation to this resource.
     *
     * ["next" => [Hal\Link]]
     *
     * @var Hal\Collection\Link
     */
    protected $links;

    /**
     * Construct a new Hal\Resource object from an array of data. You can markup the
     * data array with certain keys and values in order to affect the
     * generated JSON or XML documents if required to do so.
     *
     * "@" prefix on any array key will cause the value to be set as an
     * attribute on the XML element generated by the parent. i.e, array("x" =>
     * array("@href" => "http://url")) will yield <x href="http://url"></x> in
     * the XML representation. The @ prefix will be stripped from the JSON
     * representation.
     *
     * Specifying the key "value" will cause the value of this key to be set as
     * the value of the XML element instead of a child. i.e, array("x" =>
     * array("value" => "example")) will yield <x>example</x> in the XML
     * representation. This will not affect the JSON representation.
     *
     * @param string uri
     * @param array data
     */
    public function __construct($uri = null, $data = null) {}

    /**
     * Magic getter for data
     * @param string offset
     * @return mixed
     */
    public function __get($offset) {}

    /**
     * Get a value from data array
     * @param string offset
     * @return mixed
     */
    public function get($offset) {}

    /**
     * Magic setter for data
     * @param string offset
     * @param mixed value
     * @return mixed
     */
    public function __set($offset, $value) {}

    /**
     * Set a value in data array
     * @param string offset
     * @param mixed value
     * @return Hal\Resource
     */
    public function set($offset, $value = null) {}

    /**
     * Get resource"s URI.
     *
     * @return string
     */
    public function getUri()  {}

    /**
     * Return an array of data (key => value pairs) representing this resource.
     *
     * @return array
     */
    public function getData() {}

    /**
     * Return an array of Hal\Resource objected embedded in this one.
     *
     * @return Hal\Collection\Resource A collection of Hal\Resource
     */
    public function getResources() {}

    /**
     * Return an array of Hal\Link objects representing resources related to this one.
     *
     * @return Hal\Collection\Link A collection of Hal\Link
     */
    public function getLinks() {}

    /**
     * Add an embedded resource, identified by rel and represented by resource.
     *
     * @param string rel
     * @param Hal\Resource resource
     * @param bool multi
     * @return Hal\Resource
     */
    public function addResource($rel, Resource $resource = null, $multi = true) {}

    /**
     * Lookup and return an array of Hal\Resource objects for a given relation.
     *
     * @param string rel The resource relation required
     * @return array|bool Array of Hal\Resource objects if found. Otherwise false.
     */
    public function getResource($rel) {}

    /**
     * Add a link to the resource, identified by rel, located at uri.
     *
     * @param string rel
     * @param string uri
     * @param array attributes Other attributes, as defined by HAL spec and RFC 5988.
     * @return Hal\Resource
     */
    public function addLink($rel, $uri, $attributes = null) {}
    /**
     * Lookup and return an array of Hal\Link objects for a given relation.  Will also resolve CURIE rels if required.
     *
     * @param string rel The link relation required
     * @return array|bool Array of Hal\Link objects if found. Otherwise false.
     */
    public function getLink($rel) {}

    /**
     * Create a CURIE link template, used for abbreviating custom link relations.
     *
     * $hal->addCurie("acme", "http://.../rels/{rel}");
     * $hal->addLink("acme:test", "http://.../test");
     *
     * @param string name
     * @param string uri
     * @return Hal\Resource
     */
    public function addCurie($name, $uri) {}

    /**
     * Fetch a curie if it exists
     *
     * @param string rel
     * @todo - implement later
     */
    public function getCurie($rel) {}
}
